AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  RepositoryName:
    Default: 'ecr_repository_name'
    Type: String

Resources:
  ContainerRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName

Outputs:
  ECRRepositoryArn:
    Value: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ContainerRepository}'
